# Generated by Django 5.1.7 on 2025-03-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('tumor_image', models.ImageField(blank=True, null=True, upload_to='tumor_images/')),
                ('medical_info', models.FileField(blank=True, null=True, upload_to='medical_files/')),
                ('communication_preference', models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10, null=True)),
            ],
        ),
    ]
