# Generated by Django 5.1.7 on 2025-03-16 12:30

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_patientdata_salutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='communication_preference',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('whatsapp', 'WhatsApp')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='medical_info',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.medical_directory_path),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='tumor_image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.patient_directory_path),
        ),
    ]
